name: mango_leads
version: 1.0.2
description: Wrapper for Leads API
repository: https://github.com/louisevanderlith/leads
homepage: https://github.com/louisevanderlith/leads
environment:
  sdk: '>=2.0.0 < 3.0.0'
dependencies:
  mango_ui: '^1.0.3'